model_name: dcgan
data_root: project3_catgen/data/cats
checkpoint_dir: project3_catgen/runs
project_name: project3-catgen
run_name: dcgan_discriminator_features_128

data:
  image_size: 64

training:
  lr: 0.0002
  batch_size: 64
  num_epochs: 100
  weight_decay: 0.0
  num_workers: 0
  sample_every: 1
  checkpoint_every: 10

dcgan:
  latent_dim: 128
  generator_features: 64
  discriminator_features: 128
  beta1: 0.5
  beta2: 0.999
  label_smoothing: 0.0
  sample_grid_size: 64
