# Experiment Configuration
model_name: "custom_cnn"

# Paths
data_root: "project1_cinic10/data"
checkpoint_dir: "project1_cinic10/runs"

# Weights & Biases
project_name: "cinic10_cnn"
run_name: "custom_cnn_aug_rc_co"

# Augmentation
augmentation:
  horizontal_flip: false
  random_crop: true
  rotation: false
  cutout: true
  crop_size: 32
  crop_padding: 4
  rotation_range: 15
  cutout_size: 16
  mean: [0.4789, 0.4723, 0.4305]
  std: [0.2421, 0.2383, 0.2587]

# Training
training:
  lr: 0.001
  batch_size: 128
  num_epochs: 100
  weight_decay: 0.0001
  dropout: 0.3
  num_workers: 4